//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acorisoft.Morisa.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Acorisoft.Morisa.Properties.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 关闭创作集{0}成功 的本地化字符串。
        /// </summary>
        internal static string CompositionSetManager_Close_Success {
            get {
                return ResourceManager.GetString("CompositionSetManager_Close_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生成上下文的保存文件夹路径属性为空 的本地化字符串。
        /// </summary>
        internal static string CompositionSetManager_Generate_Context_Directory_Empty {
            get {
                return ResourceManager.GetString("CompositionSetManager_Generate_Context_Directory_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生成上下文的保存文件路径属性为空 的本地化字符串。
        /// </summary>
        internal static string CompositionSetManager_Generate_Context_FileName_Empty {
            get {
                return ResourceManager.GetString("CompositionSetManager_Generate_Context_FileName_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生成上下文的命名属性为空 的本地化字符串。
        /// </summary>
        internal static string CompositionSetManager_Generate_Context_Name_Empty {
            get {
                return ResourceManager.GetString("CompositionSetManager_Generate_Context_Name_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生成上下文为空 的本地化字符串。
        /// </summary>
        internal static string CompositionSetManager_Generate_Context_Null {
            get {
                return ResourceManager.GetString("CompositionSetManager_Generate_Context_Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生成上下文的生成属性为空 的本地化字符串。
        /// </summary>
        internal static string CompositionSetManager_Generate_Context_Property_Null {
            get {
                return ResourceManager.GetString("CompositionSetManager_Generate_Context_Property_Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载上下文的创作集目录不存在 的本地化字符串。
        /// </summary>
        internal static string CompositionSetManager_Load_Directory_NotExists {
            get {
                return ResourceManager.GetString("CompositionSetManager_Load_Directory_NotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载上下文成功，正在通知组件更新 的本地化字符串。
        /// </summary>
        internal static string CompositionSetManager_Load_Notification {
            get {
                return ResourceManager.GetString("CompositionSetManager_Load_Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载上下文成功，正在打开{0} 的本地化字符串。
        /// </summary>
        internal static string CompositionSetManager_Load_Success {
            get {
                return ResourceManager.GetString("CompositionSetManager_Load_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 切换指定的上下文无效，上下文无效 的本地化字符串。
        /// </summary>
        internal static string CompositionSetManager_Switch_Context_Invalid {
            get {
                return ResourceManager.GetString("CompositionSetManager_Switch_Context_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 切换指定的上下文无效，上下文为空 的本地化字符串。
        /// </summary>
        internal static string CompositionSetManager_Switch_Context_Null {
            get {
                return ResourceManager.GetString("CompositionSetManager_Switch_Context_Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载上下文为空 的本地化字符串。
        /// </summary>
        internal static string DataSetManager_Load_Context_Null {
            get {
                return ResourceManager.GetString("DataSetManager_Load_Context_Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载上下文中的文件不存在 的本地化字符串。
        /// </summary>
        internal static string DataSetManager_Load_File_NotExists {
            get {
                return ResourceManager.GetString("DataSetManager_Load_File_NotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载上下文中的文件名为空 的本地化字符串。
        /// </summary>
        internal static string DataSetManager_Load_FileName_Null {
            get {
                return ResourceManager.GetString("DataSetManager_Load_FileName_Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标签工厂添加实体失败，名字{0}重复 的本地化字符串。
        /// </summary>
        internal static string TagFactory_Add_Entity_Duplicate {
            get {
                return ResourceManager.GetString("TagFactory_Add_Entity_Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标签工厂更新实体失败，目标的唯一标识符为空 的本地化字符串。
        /// </summary>
        internal static string TagFactory_Add_Entity_Id_Empty {
            get {
                return ResourceManager.GetString("TagFactory_Add_Entity_Id_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标签工厂添加实体失败，目标为空 的本地化字符串。
        /// </summary>
        internal static string TagFactory_Add_Entity_Null {
            get {
                return ResourceManager.GetString("TagFactory_Add_Entity_Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标签工厂添加实体失败，父级元素{0}不存在 的本地化字符串。
        /// </summary>
        internal static string TagFactory_Add_Entity_Parent_NotExists {
            get {
                return ResourceManager.GetString("TagFactory_Add_Entity_Parent_NotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标签工厂添加实体失败，父级元素为空 的本地化字符串。
        /// </summary>
        internal static string TagFactory_Add_Entity_Parent_Null {
            get {
                return ResourceManager.GetString("TagFactory_Add_Entity_Parent_Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标签工厂移除实体失败，目标为空 的本地化字符串。
        /// </summary>
        internal static string TagFactory_Remove_Entity_Null {
            get {
                return ResourceManager.GetString("TagFactory_Remove_Entity_Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标签工厂更新实体失败，目标的唯一标识符为空 的本地化字符串。
        /// </summary>
        internal static string TagFactory_Update_Entity_Id_Empty {
            get {
                return ResourceManager.GetString("TagFactory_Update_Entity_Id_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标签工厂更新实体失败，目标为空 的本地化字符串。
        /// </summary>
        internal static string TagFactory_Update_Entity_Null {
            get {
                return ResourceManager.GetString("TagFactory_Update_Entity_Null", resourceCulture);
            }
        }
    }
}
