using System.Windows.Markup;

[assembly: XmlnsDefinition("https://github.com/Acorisoft/Acorisoft/Windows", "Acorisoft.Extensions.Platforms.Windows")]
[assembly: XmlnsDefinition("https://github.com/Acorisoft/Acorisoft/Windows", "Acorisoft.Extensions.Platforms.Windows.Controls")]
[assembly: XmlnsDefinition("https://github.com/Acorisoft/Acorisoft/Windows", "Acorisoft.Extensions.Platforms.Windows.Controls.ActivityIndicator")]
[assembly: XmlnsDefinition("https://github.com/Acorisoft/Acorisoft/Windows", "Acorisoft.Extensions.Platforms.Windows.Controls.Buttons")]
[assembly: XmlnsDefinition("https://github.com/Acorisoft/Acorisoft/Windows", "Acorisoft.Extensions.Platforms.Windows.Controls.Dialogs")]
[assembly: XmlnsDefinition("https://github.com/Acorisoft/Acorisoft/Windows", "Acorisoft.Extensions.Platforms.Windows.Controls.Panels")]
[assembly: XmlnsDefinition("https://github.com/Acorisoft/Acorisoft/Windows", "Acorisoft.Extensions.Platforms.Windows.Controls.Toasts")]
[assembly: XmlnsDefinition("https://github.com/Acorisoft/Acorisoft/Windows", "Acorisoft.Extensions.Platforms.Windows.Controls.Primitives")]
[assembly: XmlnsDefinition("https://github.com/Acorisoft/Acorisoft/Windows", "Acorisoft.Extensions.Platforms.Windows.Commands")]
[assembly: XmlnsDefinition("https://github.com/Acorisoft/Acorisoft/Windows", "Acorisoft.Extensions.Platforms.Windows.Markups")]
[assembly: XmlnsDefinition("https://github.com/Acorisoft/Acorisoft/Windows", "Acorisoft.Extensions.Platforms.Languages")]
[assembly: XmlnsDefinition("https://github.com/Acorisoft/Acorisoft/Windows", "Acorisoft.Extensions.Platforms.Windows.Views")]
[assembly: XmlnsDefinition("https://github.com/Acorisoft/Acorisoft/Windows", "Acorisoft.Extensions.Platforms.Windows.ViewModels")]