//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acorisoft.Studio.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Acorisoft.Studio.Properties.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 打开一个项目之后您即可体验此应用，您可以通过以下几种方式来打开一个项目.
        /// </summary>
        internal static string Home_EmptyState_Subtitle {
            get {
                return ResourceManager.GetString("Home_EmptyState_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 您还未打开任何项目.
        /// </summary>
        internal static string Home_EmptyState_Title {
            get {
                return ResourceManager.GetString("Home_EmptyState_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新建项目.
        /// </summary>
        internal static string Home_NewProject {
            get {
                return ResourceManager.GetString("Home.NewProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string StickyNoteGallery_Ascending_CreationTimestamp {
            get {
                return ResourceManager.GetString("StickyNoteGallery_Ascending_CreationTimestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未命名.
        /// </summary>
        internal static string StickyNoteGallery_EmptyDocumentName {
            get {
                return ResourceManager.GetString("StickyNoteGallery_EmptyDocumentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 按创建时间升序.
        /// </summary>
        internal static string StickyNoteGallery_Sort_Ascending_CreationTimestamp {
            get {
                return ResourceManager.GetString("StickyNoteGallery_Sort_Ascending_CreationTimestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 按最后修改时间升序.
        /// </summary>
        internal static string StickyNoteGallery_Sort_Ascending_LastAccessTimestamp {
            get {
                return ResourceManager.GetString("StickyNoteGallery_Sort_Ascending_LastAccessTimestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 按名字升序.
        /// </summary>
        internal static string StickyNoteGallery_Sort_Ascending_Name {
            get {
                return ResourceManager.GetString("StickyNoteGallery_Sort_Ascending_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 无.
        /// </summary>
        internal static string StickyNoteGallery_Sort_Default {
            get {
                return ResourceManager.GetString("StickyNoteGallery_Sort_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 按创建时间降序.
        /// </summary>
        internal static string StickyNoteGallery_Sort_Descending_CreationTimestamp {
            get {
                return ResourceManager.GetString("StickyNoteGallery_Sort_Descending_CreationTimestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 按修改时间降序.
        /// </summary>
        internal static string StickyNoteGallery_Sort_Descending_LastAccessTimestamp {
            get {
                return ResourceManager.GetString("StickyNoteGallery_Sort_Descending_LastAccessTimestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 按名字降序.
        /// </summary>
        internal static string StickyNoteGallery_Sort_Descending_Name {
            get {
                return ResourceManager.GetString("StickyNoteGallery_Sort_Descending_Name", resourceCulture);
            }
        }
    }
}
